language: bash
services: docker
sudo: required

env:
  - HADOOP_VERSION=3.2.1 IMG_VERSION=v1 SHORT_TAG=3 LATEST=true

script:
  - bash build.sh
  - docker run --rm --name hadoop -d crs4/hadoop:${HADOOP_VERSION}
  - "docker exec hadoop bash -c 'until datanode_cid; do sleep 0.1; done'"
  - docker cp test/check.sh hadoop:/
  - docker exec hadoop bash /check.sh
  - docker stop hadoop
  - bash test/check_custom_conf.sh
  - docker run --rm --name hdfs -d crs4/hdfs:${HADOOP_VERSION}
  - "docker exec hdfs bash -c 'until datanode_cid; do sleep 0.1; done'"
  - "docker exec hdfs bash -c 'hdfs dfs -mkdir -p /user/$(whoami)'"
  - "docker exec hdfs bash -c 'hdfs dfs -put /etc/hosts'"
  - "docker exec hdfs bash -c 'hdfs dfs -cat hosts'"
  - docker stop hdfs
  - docker-compose up -d
  - bash test/check_compose.sh
  - docker-compose down

deploy:
  - provider: script
    script: bash push.sh
    on:
      repo: crs4/hadoop-docker
      branch: master
