language: bash
services: docker
sudo: required

env:
  - OS=alpine HADOOP_VERSION=3.2.0
  - OS=centos HADOOP_VERSION=3.2.0
  - OS=ubuntu HADOOP_VERSION=3.2.0 SHORT_TAG=3 LATEST=true
  - OS=ubuntu HADOOP_VERSION=3.1.2
  - OS=ubuntu HADOOP_VERSION=2.9.2 SHORT_TAG=2

script:
  - docker build --build-arg hadoop_version=${HADOOP_VERSION} -f Dockerfile.${OS} -t crs4/hadoop:${HADOOP_VERSION}-${OS} .
  - docker run --rm --name hadoop -d crs4/hadoop:${HADOOP_VERSION}-${OS}
  - "docker exec hadoop bash -c 'until hdfs dfsadmin -safemode wait 2>/dev/null; do sleep 0.1; done'"
  - docker cp check.sh hadoop:/
  - docker exec hadoop bash /check.sh

deploy:
  - provider: script
    script: bash push.sh
    on:
      repo: crs4/hadoop-docker
      branch: master
